### ISSUE TITLE
Trying to reproduce the results

### ISSUE THREAD

**Issue by zqaz999** [heethanjan/Feature-Generator-for-FSL#2]
Hello, I am trying to reproduce the results in your paper, but I encountered some problems in the process. I used the train_generator.py file to train the generator as described in the readme.md, but encountered a 'FileNotFoundError' error. How can I get the all_logits.pickle and all_labels.pickle files? Can you tell me how to reproduce the results in the paper? 
Best wishes

**Comment by thenukan** [comment]
Thank you for your interest in reproducing our results. You can find the instructions and necessary files in the repository at the following link:
https://github.com/thenukan/feature_extractor?tab=readme-ov-file
Please refer to the README file for detailed steps.

**Comment by zqaz999** [comment]
Thanks for your reply！
